//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phiyesa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHIYESA_AutoEntities : DbContext
    {
        public PHIYESA_AutoEntities()
            : base("name=PHIYESA_AutoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoMake> AutoMakes { get; set; }
        public virtual DbSet<AutoModel> AutoModels { get; set; }
        public virtual DbSet<AutoPart> AutoParts { get; set; }
        public virtual DbSet<AutoPartBrand> AutoPartBrands { get; set; }
        public virtual DbSet<MadeInCountry> MadeInCountries { get; set; }
        public virtual DbSet<PartCategory> PartCategories { get; set; }
        public virtual DbSet<PartSubCategory> PartSubCategories { get; set; }
    }
}
