//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phiyesa
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoPart
    {
        public int Id { get; set; }
        public string PartNo { get; set; }
        public Nullable<int> PartCategory { get; set; }
        public string Year { get; set; }
        public Nullable<int> Make { get; set; }
        public Nullable<int> Model { get; set; }
        public string PartDescription { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> MadeIn { get; set; }
        public Nullable<int> EngineType { get; set; }
        public Nullable<int> PartSubCategory { get; set; }
    }
}
